name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build
      run: npm run build
    - name: Restart PM2
      run: pm2 restart ecosystem.config.js

